// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
//! FusionSpace terminal styles for Rust command-line tools (clap 4, anstyle, anstream).
//! Generated by tools/build/kit_product.py in the fusionspace-design repository; edit there, not here.
//! ANSI roles only: the user's terminal theme decides the actual colors. See product/cli.md.
//!
//! Cargo.toml: clap = { version = "4", features = ["derive"] }, anstyle = "1", anstream = "0.6"
//!
//! ```ignore
//! #[derive(clap::Parser)]
//! #[command(styles = fs_style::CLAP_STYLES)]
//! struct Cli { #[arg(long, value_enum, default_value_t = fs_style::ColorWhen::Auto)] color: fs_style::ColorWhen }
//! // after parsing:
//! fs_style::color_choice(cli.color).write_global();
//! anstream::eprintln!("{}warning:{} the main opens late", fs_style::WARNING, fs_style::WARNING.render_reset());
//! ```

use anstyle::{AnsiColor, Style};
use clap::builder::styling::Styles;

/// Section titles, table headers, the first line of a result.
pub const HEADING: Style = Style::new().bold();
/// Commands, flags and values to type.
pub const LITERAL: Style = AnsiColor::Blue.on_default().bold();
/// <FILE>, <MOTOR> in help.
pub const PLACEHOLDER: Style = AnsiColor::Blue.on_default();
/// CONT, passed, fired.
pub const OK: Style = AnsiColor::Green.on_default();
/// Values near a limit.
pub const CAUTION: Style = AnsiColor::Yellow.on_default();
/// Warning:.
pub const WARNING: Style = AnsiColor::Yellow.on_default().bold();
/// Error:, NO CONT, failed checks.
pub const DANGER: Style = AnsiColor::Red.on_default().bold();
/// Simulated or forecast values beside measured ones.
pub const PREDICTED: Style = AnsiColor::Magenta.on_default();
/// Separators and decoration only.
pub const MUTED: Style = Style::new().dimmed();
/// `error:` prefix.
pub const ERROR: Style = DANGER;
/// `help:` prefix.
pub const HELP: Style = LITERAL;
/// `note:` prefix.
pub const NOTE: Style = HEADING;

/// clap's help and error styles in the FusionSpace roles.
pub const CLAP_STYLES: Styles = Styles::styled()
    .header(HEADING)
    .usage(HEADING)
    .literal(LITERAL)
    .placeholder(PLACEHOLDER)
    .error(ERROR)
    .valid(OK)
    .invalid(WARNING);

/// The `--color` flag.
#[derive(Clone, Copy, Debug, PartialEq, Eq, clap::ValueEnum)]
pub enum ColorWhen {
    Auto,
    Always,
    Never,
}

/// Resolve color: the flag, then NO_COLOR, then FORCE_COLOR / CLICOLOR_FORCE, then auto (anstream checks the
/// stream is a terminal and TERM isn't dumb). anstream doesn't read FORCE_COLOR itself, so it is read here.
pub fn color_choice(flag: ColorWhen) -> anstream::ColorChoice {
    match flag {
        ColorWhen::Always => return anstream::ColorChoice::Always,
        ColorWhen::Never => return anstream::ColorChoice::Never,
        ColorWhen::Auto => {}
    }
    let set = |k: &str| std::env::var_os(k).is_some_and(|v| !v.is_empty());
    if set("NO_COLOR") {
        return anstream::ColorChoice::Never;
    }
    if set("FORCE_COLOR") || std::env::var("CLICOLOR_FORCE").is_ok_and(|v| !v.is_empty() && v != "0") {
        return anstream::ColorChoice::Always;
    }
    anstream::ColorChoice::Auto
}

/// True when the brand banner may use 24-bit color.
pub fn truecolor() -> bool {
    std::env::var("COLORTERM").is_ok_and(|v| v == "truecolor" || v == "24bit")
}
